### ISSUE TITLE
Own3dIdGuard's user() method dies on error

### ISSUE THREAD

**Issue by rico-ocepek** [own3d/id#10]
Currently there is a `dd` statement leftover inside an exception handler inside the Own3dIdGuard's `user` method.

If the user is not authenticated the user method therefore does not return `null` as expected but rather dies.

![image](https://user-images.githubusercontent.com/24636384/148932376-2376fcf4-70d1-40c5-8426-a7eff58a0e94.png)

**Comment by ghostzero** [comment]
`dd` statement not within package.

**Comment by rico-ocepek** [comment]
True this was just some leftover debugging code I put in there, never actually was in the package - sorry for that :)
